version: '2'
services:

    centos-nginx:
        build: docker/nginx
        restart: always
        ports:
            - 80:80
        environment:
            - VIRTUAL_PORT=80
        volumes:
            - ./app:/app

    centos-php:
        build: docker/php
        restart: always
        volumes:
            - ./app:/app
        links:
            - db
          

    db:
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: <dbschema>
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - ./docker/.data/db:/var/lib/mysql
